### PR TITLE
Google Gemini Integration

### PR DESCRIPTION
**Pull request by nimrod4278**
Adding the option to use Gemini as your LLM for gpt-pilot

### CODE REVIEW

**Comment by senko** [comment]
Thanks for the contribution @nimrod4278 :pray:, this is awesome! 

Trying GPT Pilot with various LLMs, we've found that other than GPT4, they mostly stumble on our prompts because we're using JSON schemas to define the expected output. How does Gemini fare in that regard?

It would be great if you could post a few screenshot or copy/paste a log showing it working (ie. making it as far as the development steps and then starting to create files/run commants, I'd count that as a success).

**Comment by nimrod4278** [comment]
Hi Senko,

Thanks for the cool project.

Gemini is doing well regarding JSON schemas. I did implement a retry
mechanism for it to try and fix the json if it fails parsing it.
I noticed that usually it will get it right when asked to fix the JSON file
given.

Attached are some screenshots of it developing a very simple next js app
that managed to run.

[image: unnamed.png]
[image: unnamed.png][image: unnamed.png][image: unnamed.png][image:
unnamed.png]

**Comment by DjWarmonger** [comment]
@nimrod4278 Screenshots sent by email didn't work.

I am particularly interested in this as we're yet to see Gemini Ultra, which is said to outperform GPT-4. Even if slightly, it it can make or break the app.

**Comment by robin-collins** [comment]
i believe that an LLM agnostic approach should be considered now that the new king of the hill for code is claude 3, and there are also some amazing opensource coding LLMs available.

**Comment by marcuslimdw** [comment]
What about a pluggable interface (`ModelManager`?) that could be something like this?

```
class ModelManager(metaclass=ABCMeta)

    @classmethod
    def build() -> Self:
        pass

    def generate_completion(data, request_type, project):  # TODO: add types
        pass
```

There could then be multiple implementations `OpenAiModelManager`, `GeminiModelManager` etc. that would each own configuration (loading API keys, etc. from environment variables) and formatting requests to and responses from their APIs, including any necessary retries - I too have experienced Gemini not returning things in the format you originally requested.

**Comment by Alignment-Lab-AI** [comment]
> Thanks for the contribution @nimrod4278 🙏, this is awesome!
> 
> Trying GPT Pilot with various LLMs, we've found that other than GPT4, they mostly stumble on our prompts because we're using JSON schemas to define the expected output. How does Gemini fare in that regard?
> 
> It would be great if you could post a few screenshot or copy/paste a log showing it working (ie. making it as far as the development steps and then starting to create files/run commants, I'd count that as a success).

hello, significantly delayed response, but i would be interested in training a small open source model for this

**Comment by ssnaikr** [comment]
@nimrod4278 
Have you used gemini 1.5 pro?
How were the results?

**Comment by ArtikUA** [comment]
@nimrod4278 

senko in Discord said: "I can't say when the core team might do it (we have a bunch of stuff on our plate) but would love merge this if it gets into mergeable state"

Could you please update it to the state that it can be merged?

**Review by Stevo-G-Swag — APPROVED** [review]

**Comment by redline187** [comment]
@ssnaikr i was using this [https://github.com/zuisong/gemini-openai-proxy](url) but i stopped using gemini because it cannot make a simple html login page with google 2fa Candidate was blocked due to RECITATION
s

**Comment by LeonOstrez** [comment]
with v0.2 we are handling different LLMs in a new way

**Comment by nimrod4278** [comment]
> with v0.2 we are handling different LLMs in a new way

can you link to it?

**Pull request closed without merging**
