### PR TITLE
Added Azure OpenAI endpoint

### PR DESCRIPTION
**Pull request by sander110419**
Added the required ENV variables including a switch so it supports both OpenAI API keys and Azure endpoints.
Can confirm that using the gpt4-32k is a BIG improvement to reliability.

### CODE REVIEW

**Comment by klehmann** [comment]
I tried this PR with our deployed gpt-4-32k model (version 0613) and got this:
```
There was a problem with request to openai API:
API responded with status code: 404. Response text: {
  "error": {
    "message": "Unrecognized request argument supplied: functions",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```
Do you have a newer version?

**Comment by sander110419** [comment]
> I tried this PR with our deployed gpt-4-32k model on Azure (version 0613) and got this:
> 
> ```
> There was a problem with request to openai API:
> API responded with status code: 404. Response text: {
>   "error": {
>     "message": "Unrecognized request argument supplied: functions",
>     "type": "invalid_request_error",
>     "param": null,
>     "code": null
>   }
> }
> ```
> 
> Do you have a newer version?

Weird, I just tested and for me it works, maybe our Azure tenant has access to functions, which is a real possibility.
I'll test it out later this weekend to see if I can refactor it to remove the functions call

**Comment by coolsober** [comment]
> I tried this PR with our deployed gpt-4-32k model on Azure (version 0613) and got this:
> 
> ```
> There was a problem with request to openai API:
> API responded with status code: 404. Response text: {
>   "error": {
>     "message": "Unrecognized request argument supplied: functions",
>     "type": "invalid_request_error",
>     "param": null,
>     "code": null
>   }
> }
> ```
> 
> Do you have a newer version?

"After deploying gpt-4 and GPT-4-32k (version 0613)and modifying the .env, I wanted to test it, but I ended up with the same error message as you. Why? I didn't delve deeply into the gpt-pilot code."

**Comment by sander110419** [comment]
> > I tried this PR with our deployed gpt-4-32k model on Azure (version 0613) and got this:
> > ```
> > There was a problem with request to openai API:
> > API responded with status code: 404. Response text: {
> >   "error": {
> >     "message": "Unrecognized request argument supplied: functions",
> >     "type": "invalid_request_error",
> >     "param": null,
> >     "code": null
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you have a newer version?
> 
> After deploying gpt-4 and GPT-4-32k (version 0613)and modifying the .env, I wanted to test it, but I ended up with the same error message as you. Why? I didn't delve deeply into the gpt-pilot code.

I checked it out and my Azure OpenAI tenant has access to functions, but it seems this is not generally available yet. For now this is only usable  for tenants with functions enabled, otherwise we need to wait until gpt-pilot is no longer dependant on functions, which will take some time.

**Comment by coolsober** [comment]
> > > I tried this PR with our deployed gpt-4-32k model on Azure (version 0613) and got this:
> > > ```
> > > There was a problem with request to openai API:
> > > API responded with status code: 404. Response text: {
> > >   "error": {
> > >     "message": "Unrecognized request argument supplied: functions",
> > >     "type": "invalid_request_error",
> > >     "param": null,
> > >     "code": null
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Do you have a newer version?
> > 
> > 
> > After deploying gpt-4 and GPT-4-32k (version 0613)and modifying the .env, I wanted to test it, but I ended up with the same error message as you. Why? I didn't delve deeply into the gpt-pilot code.
> 
> I checked it out and my Azure OpenAI tenant has access to functions, but it seems this is not generally available yet. For now this is only usable for tenants with functions enabled, otherwise we need to wait until gpt-pilot is no longer dependant on functions, which will take some time.

How did you check it?
I tested the function calling according to https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling.

import os
import openai

openai.api_key = os.getenv("AZURE_OPENAI_API_KEY")
openai.api_version = "2023-07-01-preview"
openai.api_type = "azure"
openai.api_base = os.environ["AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME"]
messages= [
    {"role": "user", "content": "Find beachfront hotels in San Diego for less than $300 a month with free breakfast."}
]

functions= [
    {
        "name": "search_hotels",
        "description": "Retrieves hotels from the search index based on the parameters provided",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "The location of the hotel (i.e. Seattle, WA)"
                },
                "max_price": {
                    "type": "number",
                    "description": "The maximum price for the hotel"
                },
                "features": {
                    "type": "string",
                    "description": "A comma separated list of features (i.e. beachfront, free wifi, etc.)"
                }
            },
            "required": ["location"]
        }
    }
]

response = openai.ChatCompletion.create(
    engine="gpt-4-32k",
    messages=messages,
    functions=functions,
    function_call="auto",
)

print(response['choices'][0]['message'])


---------------------------------------------------------------------------------
I got the right response below.

{
  "function_call": {
    "arguments": "{\n  \"location\": \"San Diego\",\n  \"max_price\": 300,\n  \"features\": \"beachfront, free breakfast\"\n}",
    "name": "search_hotels"
  },
  "role": "assistant"
}

**Comment by coolsober** [comment]
After checking the source code in llm_connection.py, I change the API version to '/chat/completions?api-version=2023-07-01-preview', the response status code is 200 but I got another error.

> **There was a problem with request to openai API:**
list index out of range
>

**Comment by Uranium2** [comment]
I have the same issue, even if i change the api-version to `2023-03-15-preview` in my case. (it's the version i'm using with langchain)

**Pull request merged**
